/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-08-12 07:49:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.model.Feedback;
import java.util.List;

public final class feedbacklist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1753781338000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1754846929089L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.model.Feedback");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 List<Feedback> list=(List)session.getAttribute("fb_list"); 
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<title>Food Plaza</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String c_email=(String)session.getAttribute("c_email");
String a_email=(String)session.getAttribute("a_email");

      out.write("\r\n");
      out.write("<div id=\"templatemo_container\">\r\n");
      out.write("	<div id=\"templatemo_header\">\r\n");
      out.write("    	<div id=\"site_title\"></div>\r\n");
      out.write("    </div> <!-- end of header -->\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"templatemo_menu\">\r\n");
      out.write("    ");
if (a_email==null && c_email==null){ 
      out.write("\r\n");
      out.write("        <ul>\r\n");
      out.write("        	<li class=\"current\"><a href=\"index.jsp\"><b>Home</b></a></li>\r\n");
      out.write("            <li><a href=\"login.jsp\"><b>Log in</b></a></li>\r\n");
      out.write("            <li><a href=\"registration.jsp\"><b>Registration</b></a></li>\r\n");
      out.write("            <li><a href=\"contact.jsp\"><b>Contact</b></a></li>\r\n");
      out.write("           <!--  <li><a href=\"#\"><b>Company</b></a></li>\r\n");
      out.write("            <li ><a href=\"#\"><b>Contact</b></a></li>-->\r\n");
      out.write("        </ul>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
if (a_email!=null && c_email==null){ 
      out.write("\r\n");
      out.write("        <ul>\r\n");
      out.write("        <li><a href=\"food\"><b>FoodMenu</b></a></li>\r\n");
      out.write("        <li><a href=\"addfood.jsp\"><b>AddFood</b></a></li>\r\n");
      out.write("        <li><a href=\"customer\"><b>Customer</b></a></li>\r\n");
      out.write("        <li><a href=\"feedback\"><b>Feedback</b></a></li>\r\n");
      out.write("        <li><a href=\"changepass.jsp\"><b>ChangePassword</b></a></li>\r\n");
      out.write("        <li><a href=\"login\"><b>Logout</b></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
if (a_email==null && c_email!=null){ 
      out.write("\r\n");
      out.write("        <ul>\r\n");
      out.write("         <li><a href=\"food\"><b>FoodMenu</b></a></li>\r\n");
      out.write("        <li><a href=\"cart\"><b>Cart</b></a></li>\r\n");
      out.write("        <li><a href=\"updatecustomer.jsp\"><b>EditProfile</b></a></li>\r\n");
      out.write("        <li><a href=\"addfeedback.jsp\"><b>Feedback</b></a></li>\r\n");
      out.write("        <li><a href=\"changepass.jsp\"><b>ChangePassword</b></a></li>\r\n");
      out.write("        <li><a href=\"login\"><b>Logout</b></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<table border=\"1\" style=\"margin-top:2rem\">\r\n");
      out.write("<caption style=\"color:crimson\"><b>FeedbackList</b></caption>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>EmailId</td>\r\n");
      out.write("<td>Review</td>\r\n");
      out.write("<td>Advice</td>\r\n");
      out.write("<td>Ranks</td>\r\n");
      out.write("<td>Action</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
for(Feedback f:list){ 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>");
      out.print(f.getC_email() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(f.getReview() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(f.getAdvice() );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(f.getRanks() );
      out.write("</td>\r\n");
      out.write("<td> \r\n");
      out.write("<a href=\"feedback?action=delete&c_email=");
      out.print(f.getC_email());
      out.write("\" style=\"color:red; text-decoration:none;\">Delete</a>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
 } 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"templatemo_style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div id=\"templatemo_content\">\r\n");
      out.write("    	<span class=\"top\"></span>\r\n");
      out.write("        <div id=\"templatemo_innter_content\">\r\n");
      out.write("            \r\n");
      out.write("                <div id=\"templatemo_content_left\">\r\n");
      out.write("                    <h1>Welcome to our website</h1>\r\n");
      out.write("                <img src=\"images/templatemo_image_05.jpg\" alt=\"image\" width=\"300\" height=\"200\" />\r\n");
      out.write("                   \r\n");
      out.write("                    <p>Donec malesuada elit vel enim. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse id velit elementum mi egestas ullamcorper. Vivamus nec dui.</p>\r\n");
      out.write("                  <p>Suspendisse vitae nibh ac nunc mattis blandit. Morbi consectetur ullamcorper felis. Nulla nec elit. Aliquam et mauris. Ut euismod congue diam.</p>\r\n");
      out.write("                    <a href=\"#\">Read more...</a>\r\n");
      out.write("                    \r\n");
      out.write("                        \r\n");
      out.write("                    <div class=\"cleaner_with_height\">&nbsp;</div>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("<div id=\"templatemo_content_right\">\r\n");
      out.write("                    <h1>What's new?</h1>\r\n");
      out.write("                    <div class=\"right_column_section\">\r\n");
      out.write("	                    <h2>Special meal for you</h2>\r\n");
      out.write("                        <img src=\"images/templatemo_image_06.jpg\" alt=\"image\" />\r\n");
      out.write("                        <p>Curabitur turpis. Nulla a risus. Aliquam lectus dui, euismod id, volutpat ac, fringilla eu, ipsum.</p>\r\n");
      out.write("                        <a href=\"#\">Read more...</a>\r\n");
      out.write("                     </div>\r\n");
      out.write("                \r\n");
      out.write("                </div> <!-- end of content right -->\r\n");
      out.write("        		<div class=\"cleaner\">&nbsp;</div>\r\n");
      out.write("        </div>   \r\n");
      out.write("        <div class=\"cleaner\" style=\"background: #fff;\">&nbsp;</div> 	\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"templatemo_footer\">\r\n");
      out.write("    \r\n");
      out.write("    	<a href=\"#\">Home</a> | <a href=\"#\">Tea</a> | <a href=\"#\">Top Dishes</a> | <a href=\"#\">Company</a> | <a href=\"#\">FAQs</a> | <a href=\"#\">Contact Us</a><br />\r\n");
      out.write("        Copyright © 2024 <a href=\"#\"><strong>Your Company Name</strong></a> \r\n");
      out.write("        <!-- Credit: www.templatemo.com --></div> <!-- end of footer -->\r\n");
      out.write("<!--  Free CSS Templates by TemplateMo.com  --> \r\n");
      out.write("</div><!-- end of container -->\r\n");
      out.write("<!-- templatemo 082 tea and meal -->\r\n");
      out.write("<!-- \r\n");
      out.write("Tea And Meal Template \r\n");
      out.write("http://www.templatemo.com/preview/templatemo_082_tea_and_meal \r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
